---
- name: "Install php extensions"
  apt: name={{ item }} state=present
  with_items:
    - php-gd
    - php-dev
    - php-pear
    - php-mysql
    - php-cli
    - php-date
    - php-ssh2
    - php-xml
    - php-json
    - php-curl
    - php-mbstring
    
    
- name: "Get composer installer"
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer.php
 
- name: "Install composer"
  command: "{{ item }}"
  with_items:
    - php /tmp/installer.php
    - mv composer.phar /usr/local/bin/composer
 
- name: "Delete composer installer file"
  file:
    path: /tmp/installer.php
    state: absent
