---
- name: "Install php extensions"
  apt: name={{ item }} state=present
  with_items:
    - php-gd
    - php-dev
    - php-pear
    - php-mysql
    - php-cli
    - php-date
    - php-ssh2
    - php-xml
    - php-json
    - php-curl
    - php-mbstring

- name: "Get Composer installer"
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: 0755

- name: "Run Composer installer"
  command: export COMPOSER_HOME="$HOME/.config/composer" && php /tmp/composer-setup.php --install-dir=bin --filename=composer
