---
- name: "Install php extensions"
  apt: name={{ item }} state=present
  with_items:
    - php-gd
    - php-dev
    - php-pear
    - php-mysql
    - php-cli
    - php-date
    - php-ssh2
    - php-xml
    - php-json
    - php-curl
    - php-mbstring

- name: "Run Composer installer"
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer
  warn: False
  ignore_errors: True
