---
- name: "Update APT cache"
  apt: update_cache=yes

- name: "Install LAMP packages"
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - mysql-server
    - php
    - php-mysql
    - php-xml
    - php-cgi
    - php-gd
    - php-ssh2
    - php-curl
    - php-zip
    - php-mbstring
    - libapache2-mod-php
    - python-mysqldb
