---
- name: "Prometheus installation"
  hosts: all
  remote_user: root

  tasks:

  - name: "Create prometheus user"
    user:
      name: prometheus
      create_home: no
      system: yes
      shell: "/bin/false"
      state: present

  - name: "Create Prometheus directories"
    file:
      path: "{{ item }}"
      owner: prometheus
      group : prometheus
      state: directory
    with_items:
      - /etc/prometheus
      - /var/lib/prometheus

  - name: "Extract Prometheus Binary archive" 
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.12.0/prometheus-2.12.0.linux-amd64.tar.gz
      dest: /etc/prometheus
      owner: prometheus
      group: prometheus
      extra_opts: [--strip-components=1]
      remote_src: yes
      
  - name: "Copy Prometheus binary files to /usr/local/bin directory"
    copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      remote_src: yes
      owner: prometheus
      group: prometheus
      mode: "0755"
    with_items:
      - /etc/prometheus/prometheus
      - /etc/prometheus/promtool

  - name: "Delete Prometheus binary files to Prometheus config directory"
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/prometheus/prometheus
      - /etc/prometheus/promtool
      
  - name: "Push Prometheus systemd unit file"
    copy:
      src: /tmp/ansible/prometheus/files/prometheus.service
      dest: /etc/systemd/system/prometheus.service

  - name: "Enable and Start Prometheus service"
    service:
      name: prometheus
      state: started
      enabled: yes
...
