---
- name: "Grafana Stable installation"
  hosts: all
  remote_user: root

  tasks:

  - name: "Installation of some necessary packages"
    apt: name={{ item }} update_cache=yes state=present
    with_items:
      - apt-transport-https
      - software-properties-common
      - sqlite3

  - name: "Add Grafana gpg key repository :"
    apt_key:
      url: "https://packages.grafana.com/gpg.key"
      state: present

  - name: "Add GitLab sources repo"
    apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      state: present
      update_cache: no

  - name: "Install grafana packages from stable repository"
    apt:
      name: grafana
      state: present
      update_cache: yes

  - name: "Configure admin user "
    lineinfile:
      path: /etc/grafana/grafana.ini
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
    with_items:
      - { regex: '^;admin_user = admin', line: 'admin_user = admin' }
      - { regex: '^;admin_password = admin', line: 'admin_password = {{ grafana_admin_pass }}' }

  - name: "Enable and start Grafana Server service"
    service:
      name: "grafana-server"
      state: started
      enabled: yes

...
