---
- name: "Update APT cache"
  apt: update_cache=yes

- name: "Install MySQL Server"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python-mysqldb

- name: "Create MySQL prestashop database"
  mysql_db:
    name: prestashop
    state: present

- name: "Create MySQL prestashop user"
  mysql_user: 
    name: prestashop
    host: localhost
    password: "{{ ps_mysql_password }}"
    priv: "*.*:ALL"

- name: "Define MySQL root password"
  mysql_user:
    name: root
    login_user: root
    host: localhost
    password: "{{ root_mysql_password }}"
    update_password: always
...
