---
- name: "Install PHP packages"
  apt: 
    name: "{{ item }}" 
    state: present
    update_cache: yes
  with_items:
    - php
    - php-cli
    - php-common
    - php-fpm
    - php-curl
    - php-zip
    - php-gd
    - php-mysql
    - php-xml
    - php-mcrypt
    - php-mbstring
    - php-intl

- name: "Adjust Php FPM settings"
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "memory_limit", 'line': "memory_limit = 256M"}
    - {'regexp': "upload_max_filesize", 'line': "upload_max_filesize = 32M"}

- name: "Enable and start PHP-FPM service"
  service:
    name: php7.0-fpm
    state: restarted
    enabled: yes

...
